cbvCourseCollector/cbvCourseCollector/urls.py
from django.contrib import admin
from django.urls import path
from cbvCCApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.CourseList.as_view(),name='index'),
    path('<int:pk>/',views.CourseDetail.as_view(), name='detail'),
    path('update/<int:pk>/',views.CourseUpdate.as_view()),
    path('delete/<int:pk>/', views.CourseDelete.as_view()),
    path('create/',views.CourseCreate.as_view())
]

cbvCourseCollector/cbvCCApp/models.py
from django.db import models
from django.urls import reverse

class Course(models.Model):
    courseName=models.CharField(max_length=40,verbose_name='Tananyag Név')
    description=models.TextField(verbose_name='Tananyag Leírás')
    instructor=models.CharField(max_length=40, verbose_name='Tanár')
    rates=models.FloatField(verbose_name='Értékelés')
    
    def get_absolute_url(self):
        return reverse("index")
    

cbvCourseCollector/cbvCCApp/views.py
from cbvCCApp.models import Course
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,DetailView
from django.urls import reverse_lazy

class CourseList(ListView):
    model=Course
    template_name='cbvCCApp/index.html'
    
class CourseDetail(DetailView):
    model=Course
    template_name='cbvCCApp/detail.html'
    
class CourseUpdate(UpdateView):
    model=Course
    fields=['courseName','description','instructor','rates']
    template_name='cbvCCApp/update.html'
    
class CourseDelete(DeleteView):
    model=Course
    template_name='cbvCCApp/delete.html'
    success_url=reverse_lazy('index')
    
class CourseCreate(CreateView):
    model=Course
    fields=['courseName','description','instructor','rates']
    template_name='cbvCCApp/create.html'

cbvCourseCollector/cbvCCApp/templates/cbvCCApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css1 %}{% endblock css1 %}
    {% block css2 %}{% endblock css2 %}
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block body_block %}
    {% endblock body_block %}    
</body>
</html>

cbvCourseCollector/cbvCCApp/templates/cbvCCApp/create.html
{% extends 'cbvCCApp/base.html' %}
{% block title %}Create Course{% endblock title %}
{% block body_block %}
    <h1>Creating Course:</h1>
    <form method="post">
        <table>
            {{form.as_table}}
            {% csrf_token %}
        </table>
        <button type="submit">Create</button>
    </form>
</body>
</html>
{% endblock body_block %}

cbvCourseCollector/cbvCCApp/templates/cbvCCApp/delete.html
{% extends 'cbvCCApp/base.html' %}
{% load static %}
    {% block title %}{{course.courseName}} Deleting:{% endblock title %}
{% block body_block %}
    <h1>You deleting the {{course.courseName}} course:</h1><br>
    <h3>Are you sure to deleting the {{course.courseName}} course?</h3><br>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
    <a href="/{{course.id}}"><button>Back</button></a>
    {% endblock body_block %}

cbvCourseCollector/cbvCCApp/templates/cbvCCApp/detail.html
{% extends 'cbvCCApp/base.html' %}
{% load static %}
    {% block title %}{{course.courseName}}{% endblock title %}
{% block body_block %}
{% load my_tags %}
    <h1>Course Detail:</h1><br>
    <table>
        <tr>
            <td>Course Name :</td>
            <td>{{course.courseName}}</td>
        </tr>
        <tr>    
            <td>Course Name :</td>
            <td>{{course.description}}</td>
        </tr>
        <tr>
            <td>Course Name :</td>
            <td>{{course.instructor}}</td>
        </tr>
        <tr>
            <td>Course Name :</td>
            <td>{{course.rates}}</td>
        </tr>
    </table>
    <a href='/'><button>Tanfolyam Lista</button></a>
    <a href="/update/{{course.id}}"><button>Update</button></a>
    <a href="/delete/{{course.id}}"><button>Delete</button></a>
    {% endblock body_block %}

cbvCourseCollector/cbvCCApp/templates/cbvCCApp/index.html
{% extends 'cbvCCApp/base.html' %}
{% load static %}
{% block title %}Course List{% endblock title %}
{% block css1%}<link rel="stylesheet" href="{%static 'cbvCCApp/reset.css'%}">{% endblock css1 %}
{% block css2%}<link rel="stylesheet" href="{%static 'cbvCCApp/index.css'%}">{% endblock css2 %}
{% block body_block %}
{% load my_tags %}
    <h1>Course List:</h1>
    {% if course_list %}
    <table>
        <thead>
            <th>Course Name</th>
            <th>Description</th>
            <th>Instructor</th>
            <th>Rates</th>
        </thead>
        {% for row in course_list %}
        <tr>
            <td><a href="/{{row.id}}">{{row.courseName|firstLetter}}</a></td>
            <td>{{row.description|everyFirstLetter}}</td>
            <td>{{row.instructor}}</td>
            <td>{{row.rates}}</td>
            <td><a href="update/{{row.id}}">Update</a></td>
            <td><a href="delete/{{row.id}}">Delete</a></td>
        </tr>
        {% endfor %}
    </table><br>
    {% else %}
        <h1>Haven't got any information</h1>
    {% endif %}
    <a href="create/"><button>Create Course</button></a>
{% endblock body_block %}

cbvCourseCollector/cbvCCApp/templates/cbvCCApp/update.html
{% extends 'cbvCCApp/base.html' %}
{% load static %}
{% block title %}{{course.courseName}} Updating{% endblock title %}
{% block body_block %}
<h1>{{course.courseName}} Updating:</h1>
    <form method='post'>
        <table>
            {{form.as_table}}
            {% csrf_token %}
        </table>
        <button type="submit">Update</button>
        <a href='/'><button>Tanfolyam Lista</button></a>
    </form>
    {% endblock body_block %}