Clinical/Clinical/urls.py
from django.contrib import admin
from django.urls import path
from clinicalApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.PatientListView.as_view(),name='index'),
    path('create/',views.PatientCreateView.as_view()),
    path('update/<int:pk>/',views.PatientUpdateView.as_view()),
    path('delete/<int:pk>/',views.PatientDeleteView.as_view()),
    path('addData/<int:pk>/',views.addData),
    path('analyze/<int:pk>/',views.analyze),
]

Clinical/clinicalApp/models.py
from django.db import models

class Patient(models.Model):
    firstName=models.CharField(max_length=25)
    lastName=models.CharField(max_length=25)
    age=models.IntegerField()
    
    def __str__(self):
        return self.firstName+str(" ")+self.lastName

class ClinicalData(models.Model):
    COMPONENT_NAME=[('hw','Height/Weight'),('bp','Blood Pressure'),('heartrate','Heart Rate')]
    componentName=models.CharField(choices=COMPONENT_NAME, max_length=20)
    componentValue=models.CharField(max_length=20)
    measuredDataTime=models.DateTimeField(auto_now_add=True)
    patient=models.ForeignKey(Patient, on_delete=models.CASCADE)

Clinical/clinicalApp/forms.py
from django import forms
from clinicalApp.models import Patient,ClinicalData

class PatientForm(forms.ModelForm):
    class Meta:
        model=Patient
        fields='__all__'
        
class ClinicalForm(forms.ModelForm):
    class Meta:
        model=ClinicalData
        fields='__all__'

Clinical/clinicalApp/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from clinicalApp.models import Patient, ClinicalData
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from clinicalApp.forms import ClinicalForm


class PatientListView(ListView):
    model=Patient
    template_name='clinicalApp/index.html'
    
class PatientCreateView(CreateView):
    model=Patient
    success_url=reverse_lazy('index')
    fields=('firstName','lastName','age')
    template_name='clinicalApp/create.html'
    
class PatientUpdateView(UpdateView):
    model=Patient
    success_url=reverse_lazy('index')
    fields=('firstName','lastName','age')
    template_name='clinicalApp/update.html'
    
class PatientDeleteView(DeleteView):
    model=Patient
    success_url=reverse_lazy('index')
    template_name='clinicalApp/delete.html'
    
def addData(request,**kwargs):
    form=ClinicalForm()
    patient=Patient.objects.get(id=kwargs['pk'])
    add_dict={'form':form,'patient':patient}
    if request.method=='POST':
        form=ClinicalForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/')
    return render(request,'clinicalApp/clinicalData.html',add_dict)

def analyze(request, **kwargs):
    data=ClinicalData.objects.filter(patient_id=kwargs['pk'])
    responseData=[]
    data_dict={'data':responseData}
    for eachEntry in data:
        if eachEntry.componentName == 'hw':
            heightAndWeight=eachEntry.componentValue.split('/')
            bmi=int(heightAndWeight[0])/((int(heightAndWeight[1])/100)*(int(heightAndWeight[1])/100))
            bmiEntry=ClinicalData()
            bmiEntry.componentName='BMI'
            bmiEntry.componentValue=bmi
            responseData.append(bmiEntry)
        responseData.append(eachEntry)
    return render(request, 'clinicalApp/generateReport.html',data_dict)

Clinical/templates/clinicalApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block reset %}{% endblock reset %}
    {% block css %}{% endblock css %}
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <h1 class='name'>{% block h1 %}{% endblock h1 %}</h1>
    {% block body_block %}{% endblock body_block %}
</body>
</html>

Clinical/templates/clinicalApp/clinicalData.html
{% extends 'clinicalApp/base.html' %}
{% load static %}
{% block reset %}<link rel="stylesheet" href="{% static 'CSS/reset.css' %}">{% endblock reset %}
{% block css %}<link rel="stylesheet" href="{% static 'CSS/index.css' %}">{% endblock css %}
{% block title %}Clinical Data Creation{% endblock title %}
{% block h1 %}Patiens Details{% endblock h1 %}
{% block body_block %}
    <table>
        <tr>
            <td>First Name: </td>
            <td>{{patient.firstName}}</td>
        </tr>
        <tr>
            <td>Last Name: </td>
            <td>{{patient.lastName}}</td>
        </tr>
        <tr>
            <td>Age: </td>
            <td>{{patient.age}}</td>
        </tr>
    </table>
    <h1 class='name'>Patient Clinical Data:</h1>
    <form method="post">
        <table>
            {{form.as_table}}
            {% csrf_token %}
        </table>
        <button type="submit" class='bottom' >Save</button>
    </form>
    <a href="/"><button class='bottom'>Back</button></a>
{% endblock body_block %}

Clinical/templates/clinicalApp/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Patient</title>
</head>
<body>
    <h1>Add New Patient</h1>
    <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <button type="submit">Add Patient</button>
        <button><a href="/">Back</a></button>
    </form> 
</body>
</html>

Clinical/templates/clinicalApp/delete.html
{% extends 'clinicalApp/base.html' %}
{% load static %}
{% block reset %}<link rel="stylesheet" href="{% static 'CSS/reset.css' %}">{% endblock reset %}
{% block css %}<link rel="stylesheet" href="{% static 'CSS/index.css' %}">{% endblock css %}
{% block title %}Delete Patient{% endblock title %}
{% block h1 %}Are you really Delete this Patient?{% endblock h1 %}
{% block body_block %}
    <form method="post">
        {{patient.firstName}} {{patient.lastName}}
        {% csrf_token %}
        <p></p>
        <button class='bottom' type="submit">Delete</button>
    </form>
    <a href="/"><button class='bottom'>Back</button></a>
    {% endblock body_block %}

Clinical/templates/clinicalApp/generateReport.html
{% extends 'clinicalApp/base.html' %}
{% load static %}
{% block reset %}<link rel="stylesheet" href="{% static 'CSS/reset.css' %}">{% endblock reset %}
{% block css %}<link rel="stylesheet" href="{% static 'CSS/index.css' %}">{% endblock css %}
{% block title %}Clinical Data Report{% endblock title %}
{% block h1 %}Patien Analyzed Data{% endblock h1 %}
{% block body_block %}
<table>
    <thead>
        <th>Component Name</th>
        <th>Component Value</th>
        <th>Measure Date Time</th>
    </thead>
    {% for eachEntry in data %}
    <tr>
        <td>{{eachEntry.componentName}}</td>
        <td>{{eachEntry.componentValue}}</td>
        <td>{{eachEntry.measuredDataTime}}</td>
    </tr>
    {% endfor %}
</table>
<a href="/"><button class="bottom">Home</button></a>
{% endblock body_block %}

Clinical/templates/clinicalApp/index.html
{% extends 'clinicalApp/base.html' %}
{% load static %}
{% block reset %}<link rel="stylesheet" href="{% static 'CSS/reset.css' %}">{% endblock reset %}
{% block css %}<link rel="stylesheet" href="{% static 'CSS/index.css' %}">{% endblock css %}
{% block title %}Patient List{% endblock title %}
{% block h1 %}Patiens:{% endblock h1 %}
{% block body_block %}
    {% if patient_list %}    
    <table>
        <thead>
            <th>Id</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Age</th>
        </thead>
        {% for patient in patient_list %}
            <tr>
                <td>{{patient.id}}</td>
                <td>{{patient.firstName}}</td>
                <td>{{patient.lastName}}</td>
                <td>{{patient.age}}</td>
                <td><button><a href="/addData/{{patient.id}}">Add Data</a></button></td>
                <td><button><a href="/update/{{patient.id}}">Update</a></button></td>
                <td><button><a href="/delete/{{patient.id}}">Delete</a></button></td>
                <td><button><a href="/analyze/{{patient.id}}">Analyse</a></button></td>
            </tr>
        {% endfor %}
    </table>
    {% endif %}
    <a href="/create"><button class='bottom'>Add Patient</button></a>
    {% endblock body_block %}

Clinical/templates/clinicalApp/update.html
{% extends 'clinicalApp/base.html' %}
{% load static %}
{% block reset %}<link rel="stylesheet" href="{% static 'CSS/reset.css' %}">{% endblock reset %}
{% block css %}<link rel="stylesheet" href="{% static 'CSS/index.css' %}">{% endblock css %}
{% block title %}Update Patient Data{% endblock title %}
{% block h1 %}Update Patient Data{% endblock h1 %}
{% block body_block %}
    <form method="post">
        <table>
            {{form.as_table}}
            {% csrf_token %}
        </table>
        <button class='bottom' type="submit">Update</button>
    </form>
    <a href="/"><button class='bottom'>Back</button></a>
{% endblock body_block %}